### ISSUE TITLE
mlogit: Error in multilogit

### ISSUE THREAD

**Issue by cchoirat** [IQSS/ZeligChoice#15] opened 2016-10-04 03:08 UTC
See: https://groups.google.com/forum/#!topic/zelig-statistical-software/gecXAmYXmJM.

``` r
library(Zelig)
library(ZeligChoice)

data(mexico)

z.out <- zelig(as.factor(vote88) ~ pristr + othcok + othsocok,
               model = "mlogit", data = mexico)
x.out <- setx(z.out)
s.out <- sim(z.out, x.out)
```

gives:

``` r
Error in multilogit(eta, refLevel = extra$use.refLevel, inverse = TRUE) : 
  the length of 'refLevel' must be one
```

In function `ev.mlogit` in file https://github.com/IQSS/ZeligChoice/blob/master/R/model-mlogit.R, we define `linkinv <- fitted@family@linkinv`, which seems to cause the problem.

**Comment by christophergandrud** [comment] 2017-02-06 11:24
I did a bit more digging and I think the issue might because the `linkinv` function requires two arguments, only the first of which is given a value in https://github.com/IQSS/ZeligChoice/blob/master/R/model-mlogit.R#L126.

This is the `linkinv` function:

```r
function (eta, extra = NULL) 
{
    if (anyNA(eta)) 
        warning("there are NAs in eta in slot inverse")
    ans <- multilogit(eta, refLevel = extra$use.refLevel, inverse = TRUE)
    if (anyNA(ans)) 
        warning("there are NAs here in slot linkinv")
    if (min(ans) == 0 || max(ans) == 1) 
        warning("fitted probabilities numerically 0 or 1 occurred")
    label.cols.y(ans, colnames.y = extra$colnames.y, NOS = 1)
}
``` 

So the `extra` argument expects an object with a `use.refLevel` argument, which currently isn't passed to it.

**Comment by christophergandrud** [comment] 2017-02-06 11:32
Just confirmed this by hard coding the reference level:

```r
  TEST <- NULL
  TEST$use.refLevel <- 1
  ev <- linkinv(sim.eta, extra = TEST)
```

This then produces simulations and allows `graph`:

![rplot](https://cloud.githubusercontent.com/assets/1285805/22645638/47f659a8-ec68-11e6-922a-8527b1dec200.png)

**Comment by christophergandrud** [comment] 2017-02-06 11:38
Ok, I think this solves it:

```r
  ev <- linkinv(sim.eta, extra = fitted@extra)
```

`fitted` is the fitted model object passed to `ev.mlogit` it contains the `extra` element which then contains the `use.refLevel` element needed by `linkinv`.

**Comment by christophergandrud** [comment] 2017-02-06 11:57
Should now be fixed in b2b39b915e91f213b7a3c8babe2f8ed6d9f8ec04.

**Closed by christophergandrud** 2017-02-06 11:57 UTC
Labels: bug

**Comment by christophergandrud** [comment] 2017-02-06 12:02
If everyone's ok with this, I'll push this bug fix to CRAN as it is pretty important.

**Comment by cchoirat** [comment] 2017-02-06 12:06
I agree.

**Comment by christophergandrud** [comment] 2017-02-06 12:21
Cool, headed to CRAN now.
